name: Output Project 
on: issues 
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print github contexts
        run: echo "${{ toJSON(github) }}"
      - name: Print event details
        run: echo "${{ toJSON(github.event) }}"